### ISSUE TITLE
Setting and resetting keybindings

### ISSUE THREAD

**Issue by CodeAsm** [blankstorm/blankstorm#19]
I accidentally set the ingame menu to 't' 
this now opens chat, together with the ingame menu. which isnt ideal

2 ideas,
- prevent setting the same key for a different function and 
- reset back to a defaults.

**Comment by james-pre** [comment]
> prevent setting the same key for a different function

I think this could be difficult to implement. Additionally, mods may want to do something that involves setting two keybinds to the same value.

> reset back to a defaults.

I really like this idea. At the moment, the settings sections are generated dynamically, so introducing a button for this may be difficult. I will add an option to reset all of the settings to the default. For now, you can delete `settings.json` to reset them.

**Comment by CodeAsm** [comment]
yeah i figured nuking the settings.json for now works. the mods idea might not be bad, i dunno if its tricky to do an in menu highlight of 2 same keybindings, but accepting it if saved. this might alert a user, otherwise maybe unaware (i also pressed by accident and had no idea what the original keybinding was. 🤭
